version: '3.9'

services:
  api:
    container_name: api
    build: ./wb-price-tracker-api
    restart: always
    ports:
      - '8085:8085'
    depends_on:
      - postgres
      - kafka
    environment:
      TZ: Europe/Moscow
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wb-price-tracker-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      FRONTEND_PORT: 8088

  parser:
    container_name: parser
    build: ./wb-price-tracker-parser
    restart: always
    ports:
      - '8086:8086'
    depends_on:
      - api
    environment:
      TZ: Europe/Moscow
      API_HOST: api
      API_PORT: 8085
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

  frontend:
    container_name: frontend
    build: ./wb-price-tracker-frontend
    restart: always
    ports:
      - '8088:8088'
    depends_on:
      - api
      - parser

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wb-price-tracker-db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: